// redesign/redesign/components/Contato.jsx
// Contato
const Contato = () => {
  return (
    <section className="contato wrap" id="contato" data-screen-label="Contato">
      <div className="contato-grid">
        <div>
          <div className="section-eyebrow">006 · Vem treinar</div>
          <h2 className="contato-title" style={{marginTop: 20}}>
            Entre em<br/><em>contato</em>
          </h2>
          <p className="contato-sub">
            Tire suas dúvidas, conheça os horários e locais ou nos chame
            no WhatsApp. Estamos sempre prontos para receber você.
          </p>

          <div className="contato-channels">
            <a className="channel" href="#">
              <div className="channel-icon">IG</div>
              <div className="channel-name">@amt.muaythai<small>Instagram · acompanhe</small></div>
              <div className="channel-go">Seguir →</div>
            </a>
            <a className="channel" href="#">
              <div className="channel-icon">WA</div>
              <div className="channel-name">+55 12 99999-9999<small>WhatsApp · resposta rápida</small></div>
              <div className="channel-go">Chamar →</div>
            </a>
            <a className="channel" href="#">
              <div className="channel-icon">@</div>
              <div className="channel-name">contato@amt.com.br<small>Email · institucional</small></div>
              <div className="channel-go">Enviar →</div>
            </a>
          </div>
        </div>

        <form className="contato-form" onSubmit={(e) => e.preventDefault()}>
          <div className="contato-form-title">/ formulário rápido</div>
          <div className="field">
            <label>Nome</label>
            <input type="text" placeholder="Como podemos te chamar" />
          </div>
          <div className="field">
            <label>Telefone / WhatsApp</label>
            <input type="tel" placeholder="(12) 9 8888-7777" />
          </div>
          <div className="field">
            <label>Local de interesse</label>
            <input type="text" placeholder="SJC Centro / Aquarius / Caraguá..." />
          </div>
          <div className="field">
            <label>Mensagem</label>
            <textarea rows="3" placeholder="Conte para nós como podemos ajudar"></textarea>
          </div>
          <button type="submit" className="contato-submit">Enviar mensagem →</button>
        </form>
      </div>
    </section>
  );
};

window.Contato = Contato;

// src/app/pages/contato/contato.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import emailjs from '@emailjs/browser';

@Component({
  selector: 'app-contato',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './contato.component.html',
  styleUrl: './contato.component.css'
})
export class ContatoComponent {
  contatoForm: FormGroup;
  enviando = false;
  statusMensagem = '';
  statusErro = false;

  constructor(private fb: FormBuilder) {
    this.contatoForm = this.fb.group({
      nome: ['', Validators.required],
      telefone: ['', Validators.required],
      localInteresse: [''],
      mensagem: ['', Validators.required]
    });
  }

  onSubmit() {
    if (!this.contatoForm.valid) return;

    this.enviando = true;
    this.statusMensagem = '';
    this.statusErro = false;

    const { nome, telefone, localInteresse, mensagem } = this.contatoForm.value;

    emailjs.send('service_7jabldk', 'template_cozxacs', {
      from_name: nome,
      telefone,
      local_interesse: localInteresse,
      mensagem
    }, 'q-Ga2-wuL2NZZm2zX')
      .then(() => {
        this.statusMensagem = 'Mensagem enviada com sucesso! Obrigado pelo contato.';
        this.contatoForm.reset();
      })
      .catch(() => {
        this.statusErro = true;
        this.statusMensagem = 'Ocorreu um erro ao enviar. Tente novamente mais tarde.';
      })
      .finally(() => { this.enviando = false; });
  }
}

<!-- ═══════════ CONTATO ═══════════ -->
<section class="contato-section">
  <div class="wrap">
    <div class="contato-grid">

      <!-- Left: info + channels -->
      <div class="contato-left">
        <div class="section-eyebrow"><span>006 · Vem Treinar</span></div>
        <h2 class="contato-title">
          <span class="word-white">Entre em</span>
          <em class="word-red">Contato</em>
        </h2>
        <p class="contato-sub">
          Tire suas dúvidas, conheça os horários e locais ou nos chame
          no WhatsApp. Estamos sempre prontos para receber você.
        </p>

        <div class="contato-channels">
          <a class="channel" href="https://www.instagram.com/amt_alliancemuaythai" target="_blank">
            <div class="channel-icon">IG</div>
            <div class="channel-name">
              &#64;amt.muaythai
              <small>Instagram · acompanhe</small>
            </div>
            <div class="channel-go">Seguir →</div>
          </a>
          <a class="channel" href="https://wa.me/5512991016632" target="_blank">
            <div class="channel-icon">WA</div>
            <div class="channel-name">
              +55 12 99101-6632
              <small>WhatsApp · resposta rápida</small>
            </div>
            <div class="channel-go">Chamar →</div>
          </a>
        </div>
      </div>

      <!-- Right: form -->
      <form class="contato-form" [formGroup]="contatoForm" (ngSubmit)="onSubmit()">
        <div class="contato-form-title">/ Formulário Rápido</div>

        <div class="field">
          <label>Nome</label>
          <input type="text" formControlName="nome" placeholder="Como podemos te chamar" />
        </div>
        <div class="field">
          <label>Telefone / WhatsApp</label>
          <input type="tel" formControlName="telefone" placeholder="(12) 9 8888-7777" />
        </div>
        <div class="field">
          <label>Local de Interesse</label>
          <input type="text" formControlName="localInteresse" placeholder="SJC Centro / Aquarius / Caraguá..." />
        </div>
        <div class="field">
          <label>Mensagem</label>
          <textarea formControlName="mensagem" rows="3" placeholder="Conte para nós como podemos ajudar"></textarea>
        </div>

        <button type="submit" class="contato-submit" [disabled]="!contatoForm.valid || enviando">
          {{ enviando ? 'Enviando...' : 'Enviar Mensagem →' }}
        </button>

        <div *ngIf="statusMensagem" class="status-msg" [class.sucesso]="!statusErro" [class.erro]="statusErro">
          {{ statusMensagem }}
        </div>
      </form>

    </div>
  </div>
</section>
